- name: set up fedora workstation
  hosts: localhost
  tasks:
    - name: install apps
      become: yes
      ansible.builtin.dnf:
        name:
          - 1password
          - uv
          - chezmoi
          - discord
          - thonny
          - fastfetch
          - lsd
        state: latest

    - name: set up environment
      community.general.kdeconfig:
        path: 
